apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mktxp
  labels:
    app.kubernetes.io/name: mktxp
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mktxp
  endpoints:
  - port: http
    interval: 15s
    scrapeTimeout: 10s
